echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_NAME} ;"  >> /prueba.sql
echo "CREATE USER IF NOT EXISTS ${MYSQL_ADMIN_USER} IDENTIFIED BY ${MYSQL_USER_PASSWORD};" >> /prueba.sql
echo "GRANT ALL PRIVILEGES ON *.* TO ${MYSQL_ADMIN_USER} IDENTIFIED BY ${MYSQL_USER_PASSWORD};" >> /prueba.sql
echo "FLUSH PRIVILEGES;" >> /prueba.sql
echo "ALTER USER root@localhost IDENTIFIED BY ${MYSQL_ROOT_PASSWORD};" >> /prueba.sql

#echo "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_NAME ;" >> /prueba.sql