version : "3"
services :
  mariadb :  
    build :
      context : "./srcs/mysql"
      args :
        MYSQL_DATABASE_NAME : $MYSQL_DATABASE_NAME
        MYSQL_ADMIN_USER : $MYSQL_ADMIN_USER
        MYSQL_USER_PASSWORD : $MYSQL_USER_PASSWORD
        MYSQL_ROOT_PASSWORD : $MYSQL_ROOT_PASSWORD
    container_name : mariadb
    env_file: .env
    restart : "always"
    volumes :
      - mysql:/var/lib/mysql
    networks:
      - database
  wordpress :
    build : "./srcs/wordpress"
    container_name : wordpress
    env_file: .env
    restart : "always"
    ports :
      - "8089:80"
    depends_on :
      - mariadb      
    networks:
      - database
volumes:
  mysql :
networks:
  database:
