version : "3"
services :
  mariadb :  
    build : "./srcs/mysql"
#    image : mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes :
      - "./srcs/permanent_data/mysql:/archivo_prueba"