version : "3"
services :
  mariadb :  
    build :
      context : "./srcs/mysql"
      args :
        MYSQL_DATABASE_NAME : $MYSQL_DATABASE_NAME
        MYSQL_ADMIN_USER : $MYSQL_ADMIN_USER
        MYSQL_USER_PASSWORD : $MYSQL_USER_PASSWORD
        MYSQL_ROOT_PASSWORD : $MYSQL_ROOT_PASSWORD
    container_name : mariadb
    env_file: .env
    restart : "always"
    volumes :
      - mysql:/var/lib/mysql
    networks:
      - 42_network
  wordpress :
    build : "./srcs/wordpress"
    container_name : wordpress
    env_file: .env
    depends_on :
      - mariadb
    volumes :
      - web:/var/www/html
    networks:
      - 42_network
  nginx :  
    build :
      context : "./srcs/nginx"
    container_name : nginx
    depends_on :
      - wordpress 
    links :
      - wordpress
    volumes :
      - web:/var/www/html
    networks:
      - 42_network
    ports :
      - "8000:80"
volumes:
  mysql :
  web:
networks:
  42_network:

#    restart : "always"
    
