version : "3"
services :
  wordpress :
    build : "./srcs/wordpress"
    container_name : wordpress
    ports :
      - "8089:80"
    depends_on :
      - mariadb
    environment :    
      WORDPRESS_DB_HOST : mysql
      WORDPRESS_DB_USER : root
      WORDPRESS_DB_PASSWORD : 'pass'
      WORDPRESS_DB_NAME : wordpress
  mariadb :  
    build : "./srcs/mysql"
    container_name : mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes :
      - mysql:/var/lib/mysql
volumes:
  mysql :
