version : "3.5"
services :
  mariadb :  
    build :
      context : "./srcs/mysql"
      args :
        MYSQL_DATABASE_NAME : $MYSQL_DATABASE_NAME
        MYSQL_ADMIN_USER : $MYSQL_ADMIN_USER
        MYSQL_USER_PASSWORD : $MYSQL_USER_PASSWORD
        MYSQL_ROOT_PASSWORD : $MYSQL_ROOT_PASSWORD
    container_name : mariadb
    env_file: .env
    #restart : "always"
    volumes :
      - mysql:/var/lib/mysql
    networks:
      - 42_network
  wordpress :
    build : 
      context : "./srcs/wordpress"
    container_name : wordpress
    env_file: .env
    restart : "always"
    depends_on :
      - mariadb
    volumes :
      - web:/var/www/html
    networks:
      - 42_network
  nginx :  
    build :
      context : "./srcs/nginx"
    container_name : nginx
    depends_on :
      - wordpress 
    links :
      - wordpress
    restart : "always"
    volumes :
      - web:/var/www/html
    networks:
      - 42_network
    ports :
      - "443:443"
volumes:
  mysql :
    driver: local
    driver_opts:
      o: 'bind'
      type : "none"
      device: '/home/mortiz-d/data/mysql'
  web:
    driver: local
    driver_opts:
      o: 'bind'
      type : "none"
      device: '/home/mortiz-d/data/web'
networks:
  42_network: